---
- hosts: [TEST]
  tasks:
#  - name: run platform-specific module
#    action: "linux_mymodule.py"
#  ansible_user: administrator
#  ansible_password: *****
#  ansible_port: 5985
#  ansible_connection: winrm
#  ansible_winrm_scheme: http
#  ansible_winrm_server_cert_validation: ignore
#  - name: shell
#    shell: wget -r --user='svnuser' --password='******' path/to/file
#   dest: /root/playbooks
#    remote_src: no
  - name: FTP
    get_url:
     url: ftp://****
#     force_basic_auth: true
     url_username: svnuser
     url_password: ****
#     use_proxy: true
#     validate_certs: true
     dest: /root/playbooks
     remote_src: yes
#  - name: copy
#    copy:
#     src: /opt/tomcat/lib/fusionlib/coreUtil.jar
#     dest: /opt/
#     remote_src: yes
#  - name: remove
#    command: rm /opt/tomcat/lib/fusionlib/coreUtil.jar
#  - name: copy
#    copy:
#     src: /home/centos/coreUtil.jar
#     dest: /opt/tomcat/lib/fusionlib/
