--- 
- hosts: kavin
  tasks:
    - name: install yum Utilities
      yum:
        name: yum-utils
        state: latest
    - name: adding repos
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      become: yes
        
#    - name: Enable dokcer edge
#      ini_file:
#        dest: /etc/yum.repos.d/docker-ce.repo
#        section: 'docker-ce-edge'
#        option: enabled
#        value: 0
#      become: yes
#    - name: Enable Docker Test repo
#      ini_file:
#        dest: /etc/yum.repos.d/docker-ce.repo
#        section: 'docker-ce-test'
#        option: enabled
#        value: 0
#      become: yes
    - name: yum Update
      yum:
        name: '*'
        state: present
    - name: install docker-ce
      yum:
        name: docker-ce
        state: latest
      become: yes
    - name: start docker service
      service:
        name: docker
        state: started
        enabled: yes 
