---
- hosts: [TEST]
  vars:
    namespace: ansible
    ftp_username: username
    ftp_password: '*****'
    ftp_location: url"{{ location }}"
    tomcat_dir: /exterro/services/tomcat
    patch_dir:  /root/patch_`date +%F.%H:%M:%S`
  tasks:
    actions: shell mkdir -p /root/patch_`date +%F.%H:%M:%S`
    actions: cd "{{ patch_dir }}"
    shell: wget --user= "{{ ftp_username }}" --password= "{{ftp_password }}" ftp:// "{{ ftp_location }}" "{{ location }}"
    
